name: photos
description: A Google Photos leanback experience
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file: any
  google_sign_in: any
  scoped_model: any
  http: any
  json_annotation: any
  path: any
  path_provider: any
  video_player: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any
  json_serializable: any

dependency_overrides:
  google_sign_in_android:
    path: /Users/tvolkert/project/flutter/plugins/packages/google_sign_in/google_sign_in_android

builders:
  json_serializable: any

flutter:
  uses-material-design: true
